<div id="dibu" align="center">
	<font class="fonts">Copyright&nbsp;(C)&nbsp;2011-2013
		&nbsp;BreezeDust(风尘), All Rights Reserved
		&nbsp;E-mail：BreezeDust@qq.com &nbsp;</font>
	<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F9e9dc6b25f8e71fc6fe20a2c65b3ed4a' type='text/javascript'%3E%3C/script%3E"));
</script>
</div>