<div id="LINKS" style="position:absolute; right:0px; top:250px; width:17px; height:100px;overflow:hidden;" onclick="show(cons++)">
<div id="linkimg"></div>
<div id="linkser">
<ul>
	<li><a href="http://www.CrazyForCode.org" target="_blank"><img src="images/cfclogo.png"  border="0" title="CrazyForCode.org"/></a></li>
	<li><a href="http://www.maiyun.net" target="_blank"><img src="images/maiyun.png" border="0" title="迈云"/></a></li>
	<li><a href="http://blog.csdn.net/hacke2" target="_blank"><img src="images/huayang.png" border="0" title="晔阳"/></a></li>
	<li><a href="http://hanguoshuai.com" target="_blank"><img src="images/yubo.png" border="0" title="宇博"/></a></li>
	<li><a href="http://www.vilic.info/" target="_blank"><img src="images/vilic.png" border="0" title="VILIC"/></a></li>
	<li><a href="http://www.mrchenhao.com/" target="_blank"><img src="images/chenhaologo.png" border="0" title="Mr.Chen"/></a></li>
</ul>
</div>
</div>