
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>英画电影</title>
    <link href="css/work.css" rel="stylesheet" />
    <link href="css/workDO.css" rel="stylesheet" />
    <link href="css/headerWork.css" rel="stylesheet" />
    <link href="css/copyD.css" rel="stylesheet" />
    <link href="css/bootstrap.min.css" rel="stylesheet"/>
    <script src="js/jquery-1.7.2.js"></script>
    
    <!--[if lt IE 9]>
<script src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
    <script>
    	$(function(){
    		$("#showData").attr("style","display:none");
			$("#closeMovie").click(function(){
				$("#showData").attr("style","display:none");});
        	});
    	
		function showMovie(url,id,tag){
			$("#showData").attr("style","display:block");
			if(tag==0){	
				$("#staticMovie").attr("style","display:none");
				$("#dynamicMovie").attr("style","display:block");
				$(":embed").attr("src",url);
			}else{
				$("#staticMovie").attr("style","display:block");
				$("#dynamicMovie").attr("style","display:none");
				$.ajax({
		             type: "GET",
		             url: "index.php?controller=movieContent&id="+id,
		             data: {id:"4"},
		             dataType: "json",
		             success: function(data){
		                         $('#staticMovie').html(data.movieContent);
		                      }
		         });
			}
		}
		
        </script>
</head>
<body>
    <!--导航2-->
    <div id="headers">
        <ul>
            <li class="wibe" id="wibe"></li>
            <li class="weixin" id="weixin"></li>
            <li class="qq" id="qq"></li>
        </ul>
        <div class="hdbank" id="wibeh">
            <h1>英画新浪微博</h1>
        </div>
        <div class="hdbank" id="weixinh">
            <h1>英画官方微信</h1>
            <img src="img/2wm.png" />
        </div>
        <div class="hdbank" id="qqh">
            <h1>腾讯QQ</h1>
        </div>
    </div>
    <div id="navOverBG"></div>
    <div id="navOverBar">
        <ul id="navOverBar_in">
            <li><a href="">团队介绍</a></li>
            <li><a href="">艺人展示</a></li>
            <li><a href="">现在报名</a></li>
        </ul>
    </div>
    <div id="navs">
        <ul>
            <li class="navHover nh4"><div class="nomal a4"></div><div class="navFont">H</div></li>
            <li class="navHover nh3"><div class="nomal a3"></div><div class="navFont">W</div></li>
            <li class="navHover nh2"><div class="nomal a2"></div><div class="navFont">T</div></li>
            <li class="navHover nh1"><div class="nomal a1"></div><div class="navFont">C</div></li>
            <li class="navHover nh0"><div class="nomal a0"></div><div class="navFont">A</div></li>
        </ul>
    </div>
    <!--导航结束-->
    <!--点击显示-->
    <div id="showData" >
        <h1>那年我们的青春</h1>
		<a style="width:20px;display:block;margin-left:97%;margin-top:-45px;background:img/close.png "id="closeMovie" href="javascript:"><img src="img/close.png" width="30px"/></a>        
        <div class="movie" id="dynamicMovie">
             <embed src="http://player.youku.com/player.php/sid/XNzE5NDc2NDEy/v.swf" allowFullScreen="true" quality="high" width="100%" height="100%" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>
        </div>
        <div class="movie" id="staticMovie">
        	静态电影
        </div>
    </div>
    <!--点击显示结束-->
    <div id="CFCcontent">
        <div class='entireDiv'>
            <div class='imLOGO'>
                <img src='images/domovie/logo.png'>
            </div>
        </div>
        <?php 
			$movies=new MOVIES_BLL();
			$result=$movies->selectByone("movieTag", 0);
			for ($i=0,$col=1;$i<$result->count;$col++){
// 				 第1列显示3行
				if($col==1)$rowNum=3;
// 				第二列显示2行
				elseif($col==2)$rowNum=2;
				else $rowNum=rand(1,3);
				if($result->count-$i<3)
					$rowNum=$result->count-$i;
				//$rowNum=1;
				if($rowNum==1){
				?>
				 <div class='entireDiv'>
				<?php 
				}elseif($rowNum==2){
				?>
				 <div class='halfDiv'>
				<?php
				}elseif($rowNum==3){
				?>
				 <div class='threeDiv'>
				<?php
				}
				for($row=0;$row<$rowNum&&$i<$result->count;$row++,$i++){
					?>
						<div class='divfirst'>
			                <div class='profileBg'></div>
			                <div class='profile baseFont'>
			                    <h3><?php echo $result->Rows[$i]['movieName']?></h3>
			                    <p><?php echo $result->Rows[$i]['movieDesc']?></p>
			                </div>
			                <img onclick="showMovie('<?php echo $result->Rows[$i]['movieURL']?>',<?php echo $result->Rows[$i]['movieID']?>,<?php echo $result->Rows[$i]['movieTag']?>)" src='<?php echo $result->Rows[$i]['movieOutImg']?>' />
            		</div>
					<?php 
				}
				
				?>
				</div>
				<?php 
			}
		?> 
<!--         <div class='threeDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/1.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/2.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/3.jpg' /> -->
<!--             </div> -->
<!--         </div> -->
<!--         <div class='halfDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/5.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/6.jpg' /> -->
<!--             </div> -->
<!--         </div> -->



<!--         <div class='threeDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/7.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/8.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/9.jpg' /> -->
<!--             </div> -->
<!--         </div> -->



<!--         <div class='threeDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/10.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/11.jpg' /> -->
<!--             </div> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/12.jpg' /> -->
<!--             </div> -->
<!--         </div> -->

<!--         <div class='entireDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/13.jpg'> -->
<!--             </div> -->
<!--         </div> -->


<!--         <div class='entireDiv'> -->
<!--             <div class='divfirst'> -->
<!--                 <div class='profileBg'></div> -->
<!--                 <div class='profile baseFont'> -->
<!--                     <h3>NIKE</h3> -->
<!--                     <p>NIKE Training Club – Sabrina Ouazani!</p> -->
<!--                 </div> -->
<!--                 <img src='images/domovie/4.jpg'> -->
<!--             </div> -->
<!--         </div> -->
    </div>
    <!--底部-->
    <div id="copyData" style="display:none">
        <div id="copyD" >
        <div id="inCopy">
            <p><span>技术支持：</span><a href="">CrazyForCode</a></p>
            <p><span>地址：北京市朝阳区双桥水郡长安1号院4号楼底商107号</span></p>
            <p><span>邮编：100024   电话：010-63988300 </span></p>
            <p><span>Copyright Image Film 2014. All Rights Reserved. 京ICP备13041287号 </span></p>
        </div>
    </div>
    </div>
    <!--底部结束-->
</body>
</html>
<script src="js/workDO.js"></script>
<script src="js/header2.js"></script>