<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BreezeDust-About</title>
<link rel="stylesheet" type="text/css" href="css/About.css" />
<!-- function -->
</head>
<body>
<div id="CEN">
	<div id="page">
		<div id="p_up">
			<div id="heder">	
			</div>
		</div>
		<div id="ban">
			<p><font class="h1"><strong>English Name: &nbsp;</strong></font><font class="h2">BreezeDust</font></p>
			<p><font class="h1"><strong>Chinese Name: &nbsp;</strong></font><font class="h2">杨力</font></p>
			<p><font class="h1"><strong>Team: &nbsp;</strong></font><font class="h2">CFC Leader</font></p>
			<p><font class="h1"><strong>Birthday: &nbsp;</strong></font><font class="h2">post-90s</font></p>
			<p><font class="h1"><strong>Living Place: &nbsp;</strong></font><font class="h2">BaNan, Chongqing</font></p>

			<p><font class="h1"><strong>Interests: &nbsp;</strong></font><font class="h2">AI, Web，Hand-painted</font></p>
			<p><font class="h1"><strong>Skills: &nbsp;</strong></font><font class="h2">HTML5 & CSS, JavaScript Basic VB C/C++/C#/ASP/PHP/JAVA/JSP &nbsp;  Node.js &nbsp;Linux</font></p>
			<p><font class="h1"><strong>Education&nbsp;Experience: &nbsp;</strong></font>
			<br /><font class="h2">Chongqing&nbsp;University&nbsp;of&nbsp;Technology,&nbsp;&nbsp;2011-now</font></p>
			<p><font class="h1"><strong>Remarks: &nbsp;</strong></font>
			<br /><font class="h2">Love&nbsp;&nbsp;Fantasy,&nbsp;Tangled,&nbsp;Freedom...</font>
			<br /><font class="h2">Life &nbsp;needs &nbsp;enthusiasm...</font>
			</p>
			<p><font class="h1"><strong>Contacts: &nbsp;</strong></font>
			<br /><font class="h2">Email&nbsp;&nbsp;BreezeDust@qq.com</font>
			<br /><font class="h2">QQ&nbsp;&nbsp;541092874</font></p>
			<div>
				<div style=" padding-left:650px; padding-top:20px;"><a href="index.php"><div class="back"></div></a></td></div>
			</div>
		</div>
<?php 
	require_once WEBROOT.'/application/views/Link/dibu.phtml';
?>
</div>
</div>
</body>
</html>