<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BreezeDust-Project</title>
<link rel="stylesheet" type="text/css" href="css/Project.css" />
<!-- #include file = "Link/Hmsg.asp" -->
</head>
<body>
	<div id="CEN">
		<div id="page">
			<div id="p_up">
				<div id="daohang">
					<a href="index.php?controller=index">Home</a>
					<a href="index.php?controller=diary">Diary</a>
					<a href="index.php?controller=project">Project</a>
					<a href="index.php?controller=about">About</a>
				</div>
			</div>
			<div id="PRO">
				<table border="0" cellspacing="0" cellpadding="0"
					style="margin-top: 10px;">
					<tr>
						<td valign="top" style="width: 200px;">
							<div class="box">
								<div class="boxTitle">分类</div>
								<div class="boxMain">
									<a class="boxA"  href="index.php?controller=project&art=1">个人项目</a> <a
										class="boxA" href="index.php?controller=project&art=2">Logo设计</a> <a
										class="boxA" href="index.php?controller=project&art=3">负责的团队项目</a> <a
										class="boxA" href="index.php?controller=project&art=4">参与的其他项目</a>
								</div>
							</div>
						</td>
						<td valign="top" style="width: 700px;">
							<?php require_once WEBROOT.'/Project/HTML/'.$this->view->selectPage.".phtml";?>
						</td>
					</tr>
				</table>
			</div>
		</div>
	<?php
		require_once WEBROOT . '/application/views/Link/dibu.phtml';
	?>
</div>
</body>
</html>
