<!DOCTYPE html>
<html lang="en">
<head>
<title>Matrix Admin</title>
<meta charset="UTF-8" />
<link rel="stylesheet" href="css/admin/bootstrap.min.css" />
<link rel="stylesheet" href="css/admin/bootstrap-responsive.min.css" />
<link rel="stylesheet" href="css/admin/colorpicker.css" />
<link rel="stylesheet" href="css/admin/datepicker.css" />
<link rel="stylesheet" href="css/admin/uniform.css" />
<link rel="stylesheet" href="css/admin/select2.css" />
<link rel="stylesheet" href="css/admin/matrix-style.css" />
<link rel="stylesheet" href="css/admin/matrix-media.css" />
<link rel="stylesheet" href="css/admin/bootstrap-wysihtml5.css" />
<link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

</head>
<body>

<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">Matrix Admin</a></h1>
</div>
<!--close-Header-part--> 



<!--close-top-serch-->
<!--left-sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> 选项</a>
   <ul>
    <li ><a href="index.php?controller=yingshi"><i
					class="icon icon-home"></i> <span>影视作品上传</span></a></li>
			<li class="active"><a href="index.php?controller=pingmian"><i
					class="icon icon-signal"></i> <span>平面作品</span></a></li>
			<li><a href="index.php?controller=yingshiList"><i
					class="icon icon-signal"></i> <span>影视作品列表</span></a></li>
			<li><a href="index.php?controller=pingmianList"><i
					class="icon icon-signal"></i> <span>平面作品列表</span></a></li>
  </ul>
</div>
<!--sidebar-menu-->

<!--main-container-part-->
<div id="content">
<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
  </div>
<!--End-breadcrumbs-->

  
  

<div class="container-fluid">
  <hr>
  <div class="row-fluid">
    <div class="span6">
      <div class="widget-box">
        <div class="widget-title"> <span class="icon"> <i class="icon-align-justify"></i> </span>
          <h5>微电影上传</h5>
        </div>
        <div class="widget-content nopadding">
          <form action="#" method="get" class="form-horizontal">
            <div class="control-group">
              <label class="control-label">电影名称 :</label>
              <div class="controls">
                <input type="text" class="span11" placeholder="电影名称" />
              </div>
            </div>
             <div class="control-group">
              <label class="control-label">图片上传：</label>
              <div class="controls">
                <input type="file" />
              </div>
            </div>
           <div class="control-group">
              <label class="control-label">类别（静态为1，动态为0）</label>
              <div class="controls">
                <input type="text" class="span11" placeholder="静态为1，动态为0" />
              </div>
            </div>
           
            <div class="control-group">
              <label class="control-label">电影链接</label>
              <div class="controls">
                <input type=""  class="span11" placeholder="电影链接"  />
              </div>
            </div>
           <div class="control-group">
              <label class="control-label">Date Picker (mm-dd)</label>
              <div class="controls">
                <div  data-date="12-02-2012" class="input-append date datepicker">
                  <input type="text" value="12-02-2012"  data-date-format="mm-dd-yyyy" class="span11" >
                  <span class="add-on"><i class="icon-th"></i></span> </div>
              </div>
            </div>
          
            <div class="control-group">
              <label class="control-label">电影内容：</label>
              <div class="controls">
                <textarea class="span11" ></textarea>
              </div>
            </div>
            <div class="form-actions">
              <button type="submit" class="btn btn-success">Save</button>
            </div>
          </form>
        </div>
      </div>
      
      
    </div>
    
  </div>
 
</div>
  
  
  
  
<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> 2014 &copy; CFC. Brought to you by <a href="http://themedesigner.in/">cfc</a> </div>
</div>

<!--end-Footer-part-->



</body>
</html>
