<!DOCTYPE html>
<html lang="en">
<head>
<title>Matrix Admin</title>
<meta charset="UTF-8" />
<link rel="stylesheet" href="css/admin/bootstrap.min.css" />
<link rel="stylesheet" href="css/admin/bootstrap-responsive.min.css" />


<link rel="stylesheet" href="css/admin/uniform.css" />

<link rel="stylesheet" href="css/admin/matrix-style.css" />
<link rel="stylesheet" href="css/admin/matrix-media.css" />
<link rel="stylesheet" href="css/admin/bootstrap-wysihtml5.css" />
<link href="font-awesome/css/font-awesome.css" rel="stylesheet" />

<style>
form {
	margin: 0;
}

textarea {
	display: block;
}
</style>
<link rel="stylesheet" href="kindeditor/themes/default/default.css" />

</head>
<body>

<!--Header-part-->
<div id="header">
  <h1><a href="dashboard.html">Matrix Admin</a></h1>
</div>
<!--close-Header-part--> 



<!--close-top-serch-->
<!--left-sidebar-menu-->
<div id="sidebar"><a href="#" class="visible-phone"><i class="icon icon-home"></i> 选项</a>
   <ul>
    <li ><a href="index.php?controller=yingshi"><i
					class="icon icon-home"></i> <span>影视作品上传</span></a></li>
			<li class="active"><a href="index.php?controller=pingmian"><i
					class="icon icon-signal"></i> <span>平面作品</span></a></li>
			<li><a href="index.php?controller=yingshiList"><i
					class="icon icon-signal"></i> <span>影视作品列表</span></a></li>
			<li><a href="index.php?controller=pingmianList"><i
					class="icon icon-signal"></i> <span>平面作品列表</span></a></li>
  </ul>
</div>
<!--sidebar-menu-->

<!--main-container-part-->
<div id="content">
<!--breadcrumbs-->
  <div id="content-header">
    <div id="breadcrumb"> <a href="index.html" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a></div>
  </div>
<!--End-breadcrumbs-->

  
  

<div class="container-fluid">
			<hr>
			<div class="row-fluid">
				<div class="span11">
					<div class="widget-box">
						<div class="widget-title">
							<span class="icon"> <i class="icon-align-justify"></i>
							</span>
							<h5>微电影上传</h5>
						</div>
						<div class="widget-content nopadding">
							<form name="upload" action="index.php?controller=yingshiupload"
								method="POST" class="form-horizontal">
								<div class="control-group">
									<label class="control-label">电影名称 :</label>
									<div class="controls">
										<input type="text" class="span11" placeholder="电影名称"
											name="moiveName" value="<?php echo $this->view->data['movieName']?>" />
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">电影描述 :</label>
									<div class="controls">
										<input type="text" class="span11" placeholder="电影描述"
											name=movieDesc value="<?php echo $this->view->data['moiveDesc']?>" />
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">图片上传：</label>
									&nbsp&nbsp&nbsp&nbsp&nbsp<input class="ke-input-text"
										type="text" id="url" value="<?php echo $this->view->data['movieOutImg']?>" readonly="readonly"
										name="moiveOutImg" /> <input type="button" id="uploadButton"
										value="Upload" />
								</div>
								<input type="text" style="display: none" class="span11" placeholder="静态为1，动态为0"
											name="moiveTag" value="1" />

								<div class="control-group">
									<label class="control-label">电影链接</label>
									<div class="controls">
										<input type="text" class="span11" placeholder="电影链接"
											name="moiveURL" value="<?php echo $this->view->data['movieURL']?>" />
									</div>
								</div>
								<div class="control-group">
									<label class="control-label">时间(yyyy-mm-dd)</label>
									<div class="controls">
										<div data-date="12-02-2012"
											class="input-append date datepicker">
											<input type="text" placeholder="yyyy-mm-dd" class="span11"
												name="moiveDate" value="<?php echo $this->view->data['movieDate']?>">
										</div>
									</div>
								</div>

								<div class="control-group">
									<label class="control-label">电影内容：</label>
									<div class="controls">
										<textarea name="content"
											style="width: 700px; height: 200px; visibility: hidden;"><?php echo $this->view->data['movieContent']?></textarea>
									</div>
									
								</div>
								<div class="form-actions">
								    <?php if($_GET['type']=='update'){?>
								    <input type="text" name="type" class="btn btn-success"
										value="<?php echo $this->view->data['movieID']?>" style="display: none" />
								    
								    <?php }
								    else{?>
									 <input type="text" name="type" class="btn btn-success"
										value="add"  style="display: none"/>
										
										<?php }?>
										<input type="submit" name="button" class="btn btn-success"
										value="保存" />
								</div>
								
							</form>
						</div>
					</div>


				</div>

			</div>

		</div>
  
  
  
  
<!--Footer-part-->

<div class="row-fluid">
  <div id="footer" class="span12"> 2014 &copy; CFC. Brought to you by <a href="http://themedesigner.in/">cfc</a> </div>
</div>

<script charset="utf-8" src="kindeditor/kindeditor-min.js"></script>
		<script charset="utf-8" src="kindeditor/lang/zh_CN.js"></script>
		<script>
		var editor;
		KindEditor.ready(function(K) {
			editor = K.create('textarea[name="content"]', {
				allowFileManager : true
			});
			
		});
		</script>
		<script>
			KindEditor.ready(function(K) {
				var uploadbutton = K.uploadbutton({
					button : K('#uploadButton')[0],
					fieldName : 'imgFile',
					url : 'kindeditor/php/upload_json.php?dir=image',
					afterUpload : function(data) {
						if (data.error === 0) {
							var url = K.formatUrl(data.url, 'absolute');
							K('#url').val(url);
						} else {
							alert(data.message);
						}
					},
					afterError : function(str) {
						alert('自定义错误信息: ' + str);
					}
				});
				uploadbutton.fileBox.change(function(e) {
					uploadbutton.submit();
				});
			});
		</script>
<!--end-Footer-part-->



</body>
</html>
